# This is my second docker-compose  assignment

services:
  webpage:
    build: . 
    container_name: app-stack
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install flask mysql-connector-python redis && python app.py"
    ports:
      - "5000:5000"
    networks:
      - stacknet        #explicit network example
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      com.example.service: "web"
      com.example.owner: "Alfaiz Mansoor"
      com.example.description: "Flask frontend app"

  db:
    image: mysql
    container_name: stack-database
    volumes:
      - stackapp-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - stacknet
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      com.example.service: "database"
      com.example.owner: "Alfaiz Mansoor"
      com.example.description: "mysql backend app"


  cache:
    image: redis
   # container_name: cache-stack
   # ports:
   #   - "6379:6379"
    volumes:
      - stackcache-volume:/data
    networks:
      - stacknet
    labels:
      com.example.service: "cache"
      com.example.owner: "Alfaiz Mansoor"
      com.example.description: "web-app cache"


volumes:
  stackapp-volume:                 #explicit volume example
  stackcache-volume: 

networks:
  stacknet:
    driver: bridge
