server {
    listen       80;
    server_name  localhost;

    # Custom health check endpoint
    location = /health {
        access_log off;
        default_type text/plain;
        return 200 'healthy';
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}

