# This is my first .yaml file
# Declaring name
name: Alfaiz-Mansoor

# Trigger
on:
  push: 
    branches: [push]
# Defining role
role: 
  build: containers
  Making: Pipelines

# Describing experience
experience: 1 years

# Learning define
learning: true
