name: server

on:
  workflow_dispatch:

server:
  runs-on: ubuntu-latest
  details:
    name: nginx
    ip: 127.0.10.0
    port: 3000

database:
  runs-on: ubuntu-latest
  details:
    name: mysql
    host: http://localhost/
    credentials:
      user: Alfaiz
      password: test123

script:
  name: startup script
  startup_script: |
    echo "Starting server..."
    systemctl start nginx
    systemctl status nginx
    echo "Server is running"

startup:
  name: start script
  startup_script2: >
    echo "Starting server..."
    systemctl start mysql
    systemctl status mysql
    echo "Server is running"

