kind: Pod
apiVersion: v1

metadata: 
  name: volume-pod

spec:
  containers:
  - name: volume
    image: busybox:latest
    command: ["sh", "-c", "while true; do echo \"[$(date +%T)] Hello from emptyDir!\" >> /data/message.txt; sleep 5; done"]
    volumeMounts:
    - name: my-volume
      mountPath: /data

  - name: log-reader
    image: busybox:latest
    command: ["sh", "-c", "sleep 2 && tail -f /data/message.txt"]
    volumeMounts:
    - name: my-volume
      mountPath: /data

  volumes:
  - name: my-volume
    emptyDir: {}
